# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: sqlite3
  database: db/dev3.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sky_test
  pool: 5
  username: root
  password:

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sky
  pool: 5
  username: root
  password:

